apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "14"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"home-dns"},"name":"home-dns","namespace":"home-dns"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"home-dns"}},"template":{"metadata":{"labels":{"app":"home-dns"}},"spec":{"containers":[{"image":"coredns/coredns:latest","imagePullPolicy":"Always","name":"coredns","ports":[{"containerPort":53,"name":"dns","protocol":"UDP"},{"containerPort":53,"name":"dns-tcp","protocol":"TCP"}],"volumeMounts":[{"mountPath":"/etc/coredns","name":"config-volume"}]}],"volumes":[{"configMap":{"name":"homedns-config"},"name":"config-volume"}]}}}}
  creationTimestamp: "2024-07-11T20:52:23Z"
  generation: 15
  labels:
    app: home-dns
  name: home-dns
  namespace: home-dns
  resourceVersion: "545019"
  uid: 49d30047-e5b2-4c4d-aad0-3dc8610d4ee2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: home-dns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-07-13T14:05:40+02:00"
      creationTimestamp: null
      labels:
        app: home-dns
    spec:
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: coredns/coredns:latest
        imagePullPolicy: Always
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: homedns-config
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-11T21:08:32Z"
    lastUpdateTime: "2024-07-11T21:08:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-11T21:08:25Z"
    lastUpdateTime: "2024-07-13T12:22:31Z"
    message: ReplicaSet "home-dns-79d8f7fc4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
