apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        log
        cache 30
        forward . 8.8.8.8 9.9.9.9
        reload
        loadbalance
    }
    vmnet.io:53 {
        file /etc/coredns/vmnet.io.zone
        log
        errors
    }
  vmnet.io.zone: |
    $ORIGIN vmnet.io.
    $TTL 1h
    @       IN  SOA     ns.vmnet.io. admin.vmnet.io. (
                              2020010510 ; Serial
                              1d         ; Refresh
                              2h         ; Retry
                              4w         ; Expire
                              1h )       ; Minimum TTL
            IN  NS      ns.vmnet.io.
    ns      IN  A       192.168.0.205
    @       IN  A       192.168.0.205
    webblog IN  CNAME   @
    netprint IN  CNAME  @
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    log\n    cache 30\n    forward . 8.8.8.8 9.9.9.9\n    reload\n    loadbalance\n}\nvmnet.io:53 {\n    file /etc/coredns/vmnet.io.zone\n    log\n    errors\n}\n","vmnet.io.zone":"$ORIGIN vmnet.io.\n$TTL 1h\n@       IN  SOA     ns.vmnet.io. admin.vmnet.io. (\n                          2020010510 ; Serial\n                          1d         ; Refresh\n                          2h         ; Retry\n                          4w         ; Expire\n                          1h )       ; Minimum TTL\n        IN  NS      ns.vmnet.io.\nns      IN  A       192.168.0.205\n@       IN  A       192.168.0.205\nwebblog IN  CNAME   @\nnetprint IN  CNAME  @\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"homedns-config","namespace":"home-dns"}}
  creationTimestamp: "2024-07-12T23:05:53Z"
  name: homedns-config
  namespace: home-dns
  resourceVersion: "543612"
  uid: 2919fcb3-2597-4b29-96cd-8033e55d7653
