apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"metallb.universe.tf/ip-allocated-from-pool":"dns-ippool","metallb.universe.tf/loadBalancerIPs":"192.168.0.53"},"name":"home-dns","namespace":"home-dns"},"spec":{"ports":[{"name":"dns","port":53,"protocol":"UDP","targetPort":53},{"name":"dns-tcp","port":53,"protocol":"TCP","targetPort":53}],"selector":{"app":"home-dns"},"type":"LoadBalancer"}}
    metallb.universe.tf/ip-allocated-from-pool: dns-ippool
    metallb.universe.tf/loadBalancerIPs: 192.168.0.53
  creationTimestamp: "2024-07-11T21:35:55Z"
  name: home-dns
  namespace: home-dns
  resourceVersion: "329527"
  uid: d958f241-ff47-4982-be87-a0c172c7f0ad
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.224.196
  clusterIPs:
  - 10.97.224.196
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    nodePort: 31993
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    nodePort: 31993
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app: home-dns
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.53
      ipMode: VIP
