apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: v1
kind: Namespace
metadata:
  name: jellystack
---
apiVersion: v1
kind: Namespace
metadata:
  name: nas
---
apiVersion: v1
kind: Namespace
metadata:
  name: notinkube
---
apiVersion: v1
kind: Namespace
metadata:
  name: bot
---
apiVersion: v1
kind: Namespace
metadata:
  name: dns
---
apiVersion: v1
kind: Namespace
metadata:
  name: home