services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    restart: always
    volumes:
      - /root/services/jellyfin/config:/config
      - /root/services/jellyfin/cache:/cache
      - type: bind
        source: /var/nfs/#0media
        target: /media
        read_only: true