apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellystack
  creationTimestamp: null
  labels:
    app: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jellyfin
    spec:
      containers:
      - image: linuxserver/jellyfin
        name: jellyfin
        ports:
        - containerPort: 8096
        volumeMounts:
          - mountPath: /config
            name: config
            readOnly: false
          - mountPath: /data/tvshows
            name: shows
            readOnly: false
          - mountPath: /data/movies
            name: movies
            readOnly: false
      volumes:
        - name: config
          hostPath:
            path: "/var/nfs/vmnet/svc/config/jellystack/jellyfin" # directory location on host
        - name: tvshows
          hostPath:
            path: "/var/nfs/#0media/shows"
        - name: movies
          hostPath:
            path: "/var/nfs/#0media/movies"
