apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellystack
  creationTimestamp: null
  labels:
    app: jellyfin
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jellyfin
    spec:
      containers:
      - image: linuxserver/jellyfin
        name: jellyfin
        ports:
        - containerPort: 8096
