apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: notinkube
spec:
  type: ExternalName
  externalName: 192.168.0.60  # External IP for Proxmox
  ports:
    - port: 8006
      protocol: TCP