apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: bazarr
  name: bazarr
  namespace: jellystack
spec:
  selector:
    app: bazarr
  ports:
    - port: 80
      targetPort: 6767
  type: LoadBalancer
  loadBalancerIP: 192.168.0.212