apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: jackett
  name: jackett
  namespace: jellystack
spec:
  selector:
    app: jackett
  ports:
    - port: 80
      targetPort: 9117
  type: LoadBalancer
  loadBalancerIP: 192.168.0.213
