apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: jellystack
  labels:
    app: jellyseer
  name: jellyseer
  namespace: jellystack
spec:
  selector:
    app: jellyseer
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.0.240