apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: jellyseerr
  name: jellyseerr
  namespace: jellystack
spec:
  selector:
    app: jellyseerr
  ports:
    - port: 80
      targetPort: 5055
  type: LoadBalancer
  loadBalancerIP: 192.168.0.220