apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: jellystack
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellystack
spec:
  selector:
    app: jellyfin
  ports:
    - port: 80
      targetPort: 8096
  type: LoadBalancer
  loadBalancerIP: 192.168.0.230