apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: radarr
  name: radarr
  namespace: jellystack
spec:
  selector:
    app: radarr
  ports:
    - port: 80
      targetPort: 7878
  type: LoadBalancer
  loadBalancerIP: 192.168.0.214