apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: jellystack
  labels:
    app: sonarr
  name: sonarr
  namespace: jellystack
spec:
  selector:
    app: sonarr
  ports:
    - port: 80
      targetPort: 8989
  type: LoadBalancer
  loadBalancerIP: 192.168.0.235
