apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: jellyfin
  name: transmission
  namespace: jellystack
spec:
  selector:
    app: transmission
  ports:
    - port: 80
      targetPort: 9091
  type: LoadBalancer
  loadBalancerIP: 192.168.0.211