apiVersion: apps/v1
kind: Deployment
metadata:
  name: muse
  namespace: bot
  labels:
    app: muse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muse
  template:
    metadata:
      labels:
        app: muse
    spec:
      containers:
        - name: muse
          image: ghcr.io/museofficial/muse:latest
          env:
            - name: DISCORD_TOKEN
              value: "token"
            - name: YOUTUBE_API_KEY
              value: "token"
            - name: SPOTIFY_CLIENT_ID
              value: "token"
            - name: SPOTIFY_CLIENT_SECRET
              value: "token"
          volumeMounts:
            - name: muse-data
              mountPath: /data
      volumes:
        - name: muse-data
          hostPath:
            path: /var/nfs/vmnet/svc/bots/muse
            type: Directory
