apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frittylab-cert
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      # Permit for miror creation in the following namespace.
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      # Automatically create a miror in the following namespace.
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  secretName: frittylab-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.frittylab.xyz"