apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: nextcloud
  loadBalancerIP: 192.168.0.82
  ports:
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 80
    - protocol: TCP
      name: "http2"
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: "idk"
      port: 8443
      targetPort: 8443

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - name: http
      targetPort: 80
      port: 80