apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: nas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - image: linuxserver/syncthing
          name: syncthing
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: nfs
      volumes:
        - name: config
          hostPath:
            path: /var/nfs/vmnet/nas/syncthing/config
        - name: nfsk
          hostPath:
            path: /var/nfs

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: syncthing
  name: syncthing
  namespace: nas
spec:
  selector:
    app: syncthing
  ports:
    - port: 80
      targetPort: 8384
  type: LoadBalancer
  loadBalancerIP: 192.168.0.208