apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:latest
          ports:
            - containerPort: 51820
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: SERVERURL
              value: auto  # Optional
            - name: SERVERPORT
              value: "51820"  # Optional
            - name: PEERS
              value: "peer1,peer2"  # Optional
            - name: PEERDNS
              value: "auto"  # Optional
#            - name: INTERNAL_SUBNET
#              value: "10.13.13.0"  # Optional
#            - name: ALLOWEDIPS
#              value: "0.0.0.0/0"  # Optional
#            - name: PERSISTENTKEEPALIVE_PEERS
#              value: ""  # Optional
#            - name: LOG_CONFS
#              value: "true"  # Optional
          volumeMounts:
            - name: wireguard-config
              mountPath: /config
#            - name: modules
#              mountPath: /lib/modules  # Optional
      volumes:
        - name: wireguard-config
          hostPath:
            path: /var/nfs/vmnet/svc/config/wireguard  # Adjust to your actual path
#        - name: modules
#          hostPath:
#            path: /lib/modules  # Optional
#      securityContext:
#        capabilities:
#          add:
#            - NET_ADMIN
#            - SYS_MODULE  # Optional
#        sysctls:
#          - name: net.ipv4.conf.all.src_valid_mark
#            value: "1"
#      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: wireguard
  name: wireguard
  namespace: vpn
spec:
  selector:
    app: wireguard
  ports:
    - port: 51820
      targetPort: 51820
  type: LoadBalancer
#  loadBalancerIP: 192.168.0.212

